version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    day: monday
    time: "05:18"
  # Should be bigger than or equal to the total number of dependencies (currently 3)
  open-pull-requests-limit: 5
  target-branch: ci/dependency-updates
  labels:
    - CI/CD
- package-ecosystem: pip
  directory: ".github/utils/"
  schedule:
    interval: weekly
    day: monday
    time: "05:20"
  # Should be bigger than or equal to the total number of dependencies (currently 3)
  open-pull-requests-limit: 5
  target-branch: ci/dependency-updates
  labels:
    - CI/CD
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "05:24"
  target-branch: ci/dependency-updates
  labels:
    - CI/CD
- package-ecosystem: github-actions
  directory: "{{ cookiecutter.project_slug }}/"
  schedule:
    interval: daily
    time: "05:34"
  target-branch: ci/dependency-updates
  labels:
    - CI/CD
