version: 2

updates:
- package-ecosystem: pip
  directories:
    - "/"
    - "/.github/utils/"
    - "/{{ cookiecutter.project_slug }}/.github/utils"
  schedule:
    interval: weekly
    day: monday
    time: "05:18"
  target-branch: master
  labels:
    - CI/CD
    - skip-changelog
  groups:
    packages:
      applies-to: version-updates
      patterns: ["*"]
    security:
      applies-to: security-updates
      patterns: ["*"]

- package-ecosystem: github-actions
  directories:
    - "/"
    - "/{{ cookiecutter.project_slug }}"
  schedule:
    interval: daily
    time: "05:24"
  target-branch: master
  labels:
    - CI/CD
    - skip-changelog
