name: CD - Check dependencies

on:
  schedule:
    # At 7:30 every Monday (5:30 UTC)
    - cron: "30 5 * * 1"
  workflow_dispatch:

jobs:
  update-dependencies:
    name: External
    if: github.repository_owner == '{{ cookiecutter.username }}'
    uses: SINTEF/ci-cd/.github/workflows/ci_check_pyproject_dependencies.yml@v2.5.2
    with:
      git_username: "{{ cookiecutter.author }}"
      git_email: "{{ cookiecutter.email }}"
      permanent_dependencies_branch: ci/dependency-updates
      python_version: "3.9"
      install_extras: "[dev]"
      pr_labels: "CI/CD"
    secrets:
      PAT: {{ "${{ secrets.RELEASE_PAT }}" }}
