name: CD - Publish

on:
  release:
    types:
    - published

jobs:
  update-and-publish:
    name: External
    if: github.repository == '{{ cookiecutter.username }}/{{ cookiecutter.project_slug }}' && startsWith(github.ref, 'refs/tags/v')
    uses: SINTEF/ci-cd/.github/workflows/cd_release.yml@v2.9.2
    with:
      # General
      git_username: "{{ cookiecutter.author }}"
      git_email: "{{ cookiecutter.email }}"
      release_branch: main

      # Publish on PyPI
      python_package: true
      python_version_build: "3.10"
      install_extras: "[dev]"
      package_dirs: "{{ cookiecutter.package_name }}"
      build_libs: flit
      build_cmd: flit build
      publish_on_pypi: false
      upload_distribution: true

      # Release new documentation
      update_docs: true
      python_version_docs: "3.10"
      doc_extras: "[docs]"
      changelog_exclude_labels: "skip-changelog,duplicate,question,invalid,wontfix"
      docs_framework: mkdocs
    secrets:
      PAT: {{ "${{ secrets.RELEASE_PAT }}" }}

  publish:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest

    # Using environments is recommended by PyPI when using Trusted Publishers
    environment:
      name: pypi  # Create this environment in your repository settings
      url: https://pypi.org/project/{{ cookiecutter.project_slug }}

    # The id-token:write permission is required by the PyPI upload action for
    # Trusted Publishers
    permissions:
      id-token: write

    steps:
      - name: Download distribution
        uses: actions/download-artifact@v4
        with:
          name: dist  # The artifact will always be called 'dist'
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
