name: CD - Publish

on:
  release:
    types:
    - published

jobs:
  update-and-publish:
    name: External
    if: github.repository == '{{ cookiecutter.username }}/{{ cookiecutter.project_slug }}' && startsWith(github.ref, 'refs/tags/v')
    uses: SINTEF/ci-cd/.github/workflows/cd_release.yml@v2.7.4
    with:
      # General
      git_username: "{{ cookiecutter.author }}"
      git_email: "{{ cookiecutter.email }}"
      release_branch: main

      # Publish on PyPI
      python_package: true
      python_version_build: "3.9"
      install_extras: "[dev]"
      package_dirs: "{{ cookiecutter.package_name }}"
      build_libs: flit
      build_cmd: flit build
      publish_on_pypi: false  # Change when ready to publish

      # Release new documentation
      update_docs: true
      python_version_docs: "3.9"
      doc_extras: "[docs]"
      docs_framework: mkdocs
    secrets:
      PyPI_token: {{ "${{ secrets.PYPI_TOKEN }}" }}
      PAT: {{ "${{ secrets.RELEASE_PAT }}" }}
