name: CI - Activate auto-merging for Dependabot PRs

on:
  pull_request_target:
    branches: [ci/dependency-updates]

jobs:
  automerge:
    name: External
    if: github.repository_owner == '{{ cookiecutter.username }}' && ( ( startsWith(github.event.pull_request.head.ref, 'dependabot/') && github.actor == 'dependabot[bot]' ) || ( github.event.pull_request.head.ref == 'ci/update-pyproject' && github.actor == '{{ cookiecutter.username }}' ) || ( github.event.pull_request.head.ref == 'pre-commit-ci-update-config' && github.actor == 'pre-commit-ci[bot]' ) )
    uses: SINTEF/ci-cd/.github/workflows/ci_automerge_prs.yml@v2.5.2
    secrets:
      PAT: {{ "${{ secrets.RELEASE_PAT }}" }}
