name: CI/CD - New updates to 'main'

on:
  push:
    branches: [main]

jobs:
  update-repository:
    name: External
    if: github.repository_owner == '{{ cookiecutter.username }}'
    uses: SINTEF/ci-cd/.github/workflows/ci_cd_updated_default_branch.yml@v2.7.4
    with:
      # General
      git_username: "{{ cookiecutter.author }}"
      git_email: "{{ cookiecutter.email }}"
      default_repo_branch: main

      # Dependencies branch
      update_dependencies_branch: true
      permanent_dependencies_branch: ci/dependency-updates

      # Documentation
      update_docs: true
      docs_framework: mkdocs
      update_python_api_ref: true
      update_docs_landing_page: true
      package_dirs: "{{ cookiecutter.package_name }}"
      python_version: "3.9"
      doc_extras: "[docs]"
      full_docs_dirs: "strategies"
      landing_page_replacement_separator: ","
      landing_page_replacements: |
        (LICENSE),(LICENSE.md)
        (compose.yml),({{ cookiecutter.scm_url }}/blob/main/compose.yml)
        (setup.cfg),({{ cookiecutter.scm_url }}/blob/main/setup.cfg)
    secrets:
      PAT: {{ "${{ secrets.RELEASE_PAT }}" }}
