name: CI - Single Dependabot PR

on:
  schedule:
    # At 8:30 every Wednesday (6:30 UTC)
    # Dependabot runs once a week (every Monday) (pip)
    # and every day (GH Actions) between 7:00 and 7:30 (5:00-5:30 UTC)
    - cron: "30 6 * * 3"
  workflow_dispatch:

jobs:
  create-collected-pr:
    name: External
    if: github.repository_owner != '{{ cookiecutter.username }}'
    uses: SINTEF/ci-cd/.github/workflows/ci_update_dependencies.yml@v2.7.4
    with:
      # General
      git_username: "{{ cookiecutter.author }}"
      git_email: "{{ cookiecutter.email }}"
      default_repo_branch: main
      permanent_dependencies_branch: ci/dependency-updates

      # pre-commit
      update_pre-commit: true
      python_version: "3.9"
      install_extras: "[dev]"

      # PR
      pr_labels: "CI/CD"
      extra_to_dos: "- [ ] Make sure that the PR is **squash** merged, with a sensible commit message."
    secrets:
      PAT: {{ "${{ secrets.RELEASE_PAT }}" }}
