# To install the git pre-commit hook run:
#   pre-commit install
# To update the pre-commit hooks run:
#   pre-commit autoupdate
# To run the pre-commit hooks manually run:
#   pre-commit run --all-files
repos:
  # pre-commit-hooks supplies a multitude of small hooks
  # To get an overview of them all as well as the ones used here, please see
  # https://github.com/pre-commit/pre-commit-hooks#hooks-available
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: end-of-file-fixer
    - id: debug-statements
    - id: check-yaml
      name: Check YAML
    - id: check-toml
      name: Check TOML
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]

  # ruff is a Python linter, incl. import sorter and formatter
  # It works partly on files in-place
  # More information can be found in its documentation:
  # https://docs.astral.sh/ruff/
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]

  # Black is a code style and formatter
  # It works on files in-place
  - repo: https://github.com/ambv/black
    rev: 23.11.0
    hooks:
    - id: black

  # Bandit is a security linter
  # More information can be found in its documentation:
  # https://bandit.readthedocs.io/en/latest/
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    - id: bandit
      args: ["-r"]
      files: ^{{ cookiecutter.package_name }}/.*$

  # mypy is a static typing linter
  # The main code repository can be found at:
  # https://github.com/python/mypy
  # The project's documentation can be found at:
  # https://mypy.readthedocs.io/en/stable/index.html
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
    - id: mypy
      exclude: ^tests/.*$
      additional_dependencies:
        - "pydantic>=2"

  # ci-cd is a collection of hooks to help with CI/CD
  # The main code repository can be found at:
  # https://github.com/SINTEF/ci-cd
  # The project's documentation can be found at:
  # https://SINTEF.github.io/ci-cd/
  - repo: https://github.com/SINTEF/ci-cd
    rev: v2.6.0
    hooks:
    - id: docs-api-reference
      args:
      - "--package-dir={{ cookiecutter.package_name }}"
      - "--docs-folder=docs"
      - "--full-docs-folder=strategies"
    - id: docs-landing-page
      args:
      - "--docs-folder=docs"
      - "--replacement-separator=,"
      - "--replacement=(LICENSE),(LICENSE.md)"
      - "--replacement=(docker-compose.yml),({{ cookiecutter.scm_url }}/blob/main/docker-compose.yml)"
      - "--replacement=(setup.cfg),({{ cookiecutter.scm_url }}/blob/main/setup.cfg)"
