site_name: "{{ cookiecutter.project_name }}"
site_description: Documentation for the {{ cookiecutter.project_name }} package
site_url: https://{{ cookiecutter.username }}.github.io/{{ cookiecutter.project_slug }}
copyright: Copyright &copy; {{ cookiecutter.year }} {{ cookiecutter.organization }}

theme:
  name: material
  palette:
    scheme: default
    primary: purple
    accent: amber
  icon:
    repo: fontawesome/brands/github
    logo: material/library-shelves
  favicon: assets/images/favicon.png
  language: en
  features:
    - navigation.instant
    - navigation.top

repo_name: "{{ cookiecutter.project_slug }}"
repo_url: "{{ cookiecutter.scm_url }}"
edit_uri: ""

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/{{ cookiecutter.username }}
      name: "{{ cookiecutter.author }} on GitHub"
  version:
    provider: mike
    default: latest

extra_css:
  - css/reference.css

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.snippets
  - toc:
      permalink: true

plugins:
  - search:
      lang: en
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            # General options
            show_bases: true
            show_source: true

            # Headings options
            heading_level: 2
            show_root_heading: false
            show_root_toc_entry: true
            show_root_full_path: true
            show_object_full_path: false
            show_category_heading: false

            # Members options
            inherited_members: false
            members: null
            filters:
              - "!^_[_]"
              - "^__init__$"
            group_by_category: true

            # Docstrings options
            docstring_style: google
            show_if_no_docstring: false

            # Signatures/annotations options
            line_length: 88
  - awesome-pages
  - autorefs:
      resolve_closest: true

watch:
  - "{{ cookiecutter.package_name }}"
