name: CI - Tests

on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:

  test-template:
    runs-on: ubuntu-latest
    name: Build cookiecutter template and run standard tests

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel
        pip install cookiecutter

    - name: Run cookiecutter
      run: cookiecutter --no-input . project_name=oteapi_ci project_slug=oteapi-ci package_name=oteapi_ci

    - name: Install template
      run: |
        pip install -r oteapi-ci/requirements.txt
        pip install -e oteapi-ci[dev]

    - name: Run pytest
      run: pytest oteapi-ci

    - name: Run pre-commit
      run: pre-commit run --all-files
      working-directory: ./oteapi-ci

    - name: Run safety
      run: |
        pip install safety
        pip freeze | safety check --stdin

  pre-commit_safety:
    runs-on: ubuntu-latest
    name: pre-commit & safety

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel
        pip install -r requirements.txt
        pip install safety

    - name: Test with pre-commit
      run: pre-commit run --all-files

    - name: Run safety
      run: pip freeze | safety check --stdin
