name: CI - Tests

on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  test-template:
    runs-on: ubuntu-latest
    name: Build cookiecutter template and run standard tests

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel flit
        pip install -r .github/utils/requirements.txt

    - name: Set up git
      run: |
        git config --global user.name "TEAM 4.0[bot]"
        git config --global user.email "Team4.0@SINTEF.no"

    - name: Run cookiecutter
      run: cookiecutter --no-input --config-file .github/utils/cookiecutter_values.yaml .

    - name: Register all template strategies
      run: |
        sed -i 's|# \"oteapi|\"oteapi|' oteapi-ci/pyproject.toml
        cat oteapi-ci/pyproject.toml

    - name: Install template
      run: pip install -e oteapi-ci[dev]

    - name: Run pytest
      run: pytest -vvv
      working-directory: ./oteapi-ci

    - name: Run pre-commit
      run: pre-commit run --all-files
      working-directory: ./oteapi-ci

    # Ignore ID 44715 for now.
    # See this NumPy issue for more information: https://github.com/numpy/numpy/issues/19038
    - name: Run safety
      run: pip freeze | safety check --stdin --ignore 44715

    - name: Build docs
      run: mkdocs build --strict
      working-directory: ./oteapi-ci

    - name: Build source distribution
      run: flit build
      working-directory: ./oteapi-ci

  pre-commit_safety:
    # Do not use SINTEF/ci-cd, since it requires the root repository to be installable
    # as a package.
    runs-on: ubuntu-latest
    name: pre-commit & safety

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel
        pip install -r requirements.txt -r .github/utils/requirements.txt

    - name: Test with pre-commit
      run: pre-commit run --all-files

    - name: Run safety
      run: pip freeze | safety check --stdin
