name: CI - Tests

on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  test-template:
    runs-on: ubuntu-latest
    name: Build cookiecutter template and run standard tests

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v5

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel
        pip install -r .github/utils/requirements.txt

    - name: Set up git
      run: |
        git config --global user.name "TEAM 4.0[bot]"
        git config --global user.email "Team4.0@SINTEF.no"

    - name: Run cookiecutter
      run: cookiecutter --no-input --config-file .github/utils/cookiecutter_values.yaml .

    - name: Register all template strategies
      run: |
        sed -i 's|# \"oteapi|\"oteapi|' oteapi-ci/pyproject.toml
        cat oteapi-ci/pyproject.toml

    - name: Install template
      run: pip install -e oteapi-ci[dev]

    # There should be no warnings, so we're treating warnings as errors
    - name: Run pytest
      run: pytest -vv --pythonwarnings="error"
      working-directory: ./oteapi-ci

    - name: Run pre-commit
      run: pre-commit run --all-files
      working-directory: ./oteapi-ci

    - name: Run pip-audit
      uses: pypa/gh-action-pip-audit@v1.1.0

    - name: Build docs
      run: mkdocs build --strict
      working-directory: ./oteapi-ci

    - name: Build source distribution
      run: flit build
      working-directory: ./oteapi-ci

  pip-audit:
    # Do not use SINTEF/ci-cd, since it requires the root repository to be installable
    # as a package.
    runs-on: ubuntu-latest
    name: pip-audit

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up Python 3.10
      uses: actions/setup-python@v6
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel
        pip install -r requirements.txt -r .github/utils/requirements.txt

    - name: Run pip-audit
      uses: pypa/gh-action-pip-audit@v1.1.0
