name: CI - Tests

on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:

  test-template:
    runs-on: ubuntu-latest
    name: Build cookiecutter template and run standard tests

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel
        pip install cookiecutter

    - name: Set up git
      run: |
        git config --global user.name "oteapi-plugin-template"
        git config --global user.email "oteapi-plugin-template@EMMC-ASBL.org"

    - name: Run cookiecutter
      run: cookiecutter --no-input --config-file .github/utils/cookiecutter_values.yaml .

    - name: Install template
      run: |
        pip install -r oteapi-ci/requirements.txt
        pip install -e oteapi-ci[dev]

    - name: Run pytest
      run: pytest -vvv
      working-directory: ./oteapi-ci

    - name: Run pre-commit
      run: pre-commit run --all-files
      working-directory: ./oteapi-ci

    # Ignore ID 44715 for now.
    # See this NumPy issue for more information: https://github.com/numpy/numpy/issues/19038
    - name: Run safety
      run: |
        pip install safety
        pip freeze | safety check --stdin --ignore 44715

    - name: Build docs
      run: |
        invoke create-api-reference-docs --pre-clean
        invoke create-docs-index
        mkdocs build --strict
      working-directory: ./oteapi-ci

  pre-commit_safety:
    runs-on: ubuntu-latest
    name: pre-commit & safety

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel
        pip install -r requirements.txt
        pip install safety

    - name: Test with pre-commit
      run: pre-commit run --all-files

    - name: Run safety
      run: pip freeze | safety check --stdin
