name: CI - New updates to 'master'

on:
  push:
    branches: [master]

jobs:
  update-dependencies-branch:
    name: External
    if: github.repository_owner == 'EMMC-ASBL'
    uses: SINTEF/ci-cd/.github/workflows/ci_cd_updated_default_branch.yml@v2.6.0
    with:
      # General
      git_username: "TEAM 4.0[bot]"
      git_email: "Team4.0@SINTEF.no"
      default_repo_branch: master

      # Dependencies branch
      permanent_dependencies_branch: ci/dependency-updates
      update_dependencies_pr_body_file: .github/utils/single_dependency_pr_body.txt

      # Documentation
      update_docs: false
    secrets:
      PAT: ${{ secrets.RELEASE_PAT }}
