name: CI - Tests

on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:

  test-template:
    runs-on: ubuntu-latest
    # timeout-minutes: 2

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cookiecutter
    - name: Run cookiecutter
      run: cookiecutter --no-input . project_name=oteapi_ci project_slug=oteapi-ci package_name=oteapi_ci
    - name: Install template
      run: |
        pip install -r oteapi-ci/requirements.txt
        pip install -e oteapi-ci
    - name: Run tests
      run: |
        pip install pytest
        pytest oteapi-ci

